[information]
 name = "blaze"
 background = "dark"
 author = 'Dean Kinane <dean.kinane@gmail.com'

[palette]
 fg = '#9892B8'
 fg_dim = '#57507C'
 fg_vivid = '#8E8EEA'
 bg = '#1F1B2B'
 bg_dark = '#121019'
 white = '#E5E5E5'
 black = '#000000'
 comment = '#4A4062'
 
 red = '#ED4760'
 pink = '#C57BA5'
 pink_vivid = '#D63585'
 orange = '#F27D58'
 yellow = '#F6C76A'
 light_blue ='#B7ECFF'
 blue ='#5091CC'
 green = '#A9D18E'
 
 temp = '#E500FF'
 alt_fg = '#8b92a8'
 dark = '#1b1f27'
 accent = '#545862'
 popup_back = '#1e222a'
 search_orange = '#613214'
 line = '#282C34'

 search_blue = '#083C5A'
 gray = '#545862'
 dark_gray = '#3e4451'
 context = '#6b737f'
 light_gray = '#c8ccd4'
 vivid_blue = '#4FC1FF'
 dark_blue = '#223E55'
 folder_blue = '#42A5F5'
 cyan = '#46a6b2'
 light_green = '#c18a56'
 light_red = '#d05c65'
 magenta = '#D16D9E'

 cursor_fg = '#1F1B2B'
 cursor_bg = '#AEAFAD'

 sign_add = '#66CE1C'
 sign_change = '#F6C76A'
 sign_delete = '#94151b'
 tree_sign_add = '#73C991'
 tree_sign_change = '#CCA700'

 error_red = '#F44747'
 warning_orange = '#ff8800'
 info_white = '#FFCC66'
 hint_blue = '#4FC1FF'
 success_green = '#14C50B'

 purple_test = '#ff007c'
 cyan_test = '#00dfff'

 ui_blue = '#264F78'
 ui2_blue = '#042E48'
 ui3_blue = '#0195F7'
 ui4_blue = '#75BEFF'
 ui_orange = '#E8AB53'
 ui_purple = '#B180D7'

[highlights]
 
 Normal = 'white bg'
 SignColumn = '- bg'
 MsgArea = 'fg bg'
 ModeMsg = 'fg dark'
 MsgSeparator = 'fg bg'
 SpellBad = 'light_red - u'
 SpellCap = 'white - u'
 SpellLocal = 'green - u'
 SpellRare = 'white - u'
 NormalNC = 'fg bg'
 Pmenu = 'light_gray bg_dark - - 50'
 PmenuSel = 'yellow bg_dark'
 WildMenu = 'fg ui2_blue'
 CursorLineNr = 'light_gray - b'
 Comment = 'comment black'
 Folded = 'accent bg_dark'
 FoldColumn = 'accent bg_dark'
 LineNr = 'comment -'
 FloatBorder = 'gray bg_dark'
 Whitespace = 'bg -'
 VertSplit = 'gray bg'
 CursorLine = '- bg_dark'
 CursorColumn = '- bg_dark'
 ColorColumn = '- bg_dark'
 NormalFloat = '- bg_dark'
 Visual = '- ui_blue'
 VisualNOS = '- bg_dark'
 WarningMsg = 'error_red bg'
 DiffAdd = 'bg_dark sign_add'
 DiffChange = 'bg_dark sign_change u'
 DiffDelete = 'bg_dark sign_delete'
 QuickFixLine = '- ui2_blue'
 PmenuSbar = '- bg_dark'
 PmenuThumb = '- gray'
 MatchWord = '- - u'
 MatchParen = 'hint_blue bg u'
 MatchWordCur = '- - u'
 MatchParenCur = '- - u'
 Cursor = 'cursor_fg cursor_bg'
 lCursor = 'cursor_fg cursor_bg'
 CursorIM = 'cursor_fg cursor_bg'
 TermCursor = 'cursor_fg cursor_bg'
 TermCursorNC = 'cursor_fg cursor_bg'
 Conceal = 'accent'
 Directory = 'blue'
 SpecialKey = 'blue - b'
 Title = 'blue - b'
 ErrorMsg = 'error_red bg b'
 Search = 'light_gray search_blue'
 IncSearch = 'search_orange light_gray'
 Substitute = 'light_gray search_orange'
 MoreMsg = 'orange'
 Question = 'orange'
 EndOfBuffer = 'bg'
 NonText = 'bg'
 Variable = 'white'
 String = 'green'
 Character = 'orange'
 Constant = 'vivid_blue'
 Number = 'light_green'
 Boolean = 'blue'
 Float = 'light_green'
 Identifier = 'fg_dim'
 Function = 'red'
 Operator = 'fg'
 Type = 'pink_vivid'
 StorageClass = 'blue'
 Structure = 'pink_vivid'
 Typedef = 'blue'
 Keyword = 'pink'
 Statement = 'fg_dim'
 Conditional = 'fg_dim'
 Repeat = 'white'
 Label = 'yellow'
 Exception = 'white'
 Include = 'white'
 PreProc = 'white'
 Define = 'white'
 Macro = 'white'
 PreCondit = 'white'
 Special = 'fg_dim'
 SpecialChar = 'white'
 Tag = 'blue'
 Debug = 'red'
 Delimiter = 'gray -'
 SpecialComment = 'gray'
 Underlined = '- - u'
 Bold = '- - b'
 Italic = '- - i'
 Ignore = 'cyan bg b'
 Todo = 'magenta bg b'
 Error = 'error_red bg b'
 TabLine = 'light_gray line'
 TabLineSel = 'white line'
 TabLineFill = 'line line'

[Treesitter]
 TSComment = 'link:Comment'
 TSAnnotation = 'blue'
 TSAttribute = 'cyan'
 TSConstructor = 'cyan'
 TSType = 'cyan'
 TSTypeBuiltin = 'white'
 TSConditional = 'white'
 TSException = 'white'
 TSInclude = 'white'
 TSKeywordReturn = 'white'
 TSKeyword = 'white'
 TSKeywordFunction = 'white'
 TSLabel = 'light_blue'
 TSNamespace = 'cyan'
 TSRepeat = 'white'
 TSConstant = 'orange'
 TSConstBuiltin = 'orange'
 TSFloat = 'orange'
 TSNumber = 'orange'
 TSBoolean = 'orange'
 TSCharacter = 'green'
 TSError = 'error_red'
 TSFunction = 'blue'
 TSFuncBuiltin = 'blue'
 TSMethod = 'blue'
 TSConstMacro = 'orange'
 TSFuncMacro = 'blue'
 TSVariable = 'white'
 TSVariableBuiltin = 'red'
 TSProperty = 'red'
 TSField = 'fg'
 TSParameter = 'red'
 TSParameterReference = 'red'
 TSSymbol = 'light_blue'
 TSText = 'alt_fg'
 TSOperator = 'alt_fg'
 TSPunctDelimiter = 'alt_fg -'
 TSTagDelimiter = 'alt_fg'
 TSTagAttribute = 'orange'
 TSPunctBracket = 'alt_fg -'
 TSPunctSpecial = 'white'
 TSString = 'green'
 TSStringRegex = 'green'
 TSStringEscape = 'green'
 TSTag = 'blue'
 TSEmphasis = '- - i'
 TSUnderline = '- - u'
 TSTitle = 'fg - -'
 TSLiteral = 'orange'
 TSURI = 'orange - u'
 TSKeywordOperator = 'white'
 TSStructure = 'light_blue'
 TSStrong = 'blue - b'
 TSQueryLinterError = 'warning_orange'
 TreesitterContext = '- bg_dark'

[typescript]
 typescriptBraces = 'white'
 typescriptParens = 'white'
 typescriptDestructureVariable = 'yellow'
 typescriptVariableDeclaration = 'yellow'
 typescriptFuncCallArg = 'white'
 typescriptBlock = 'pink'
 typescriptAssign = 'fg'
 typescriptBinaryOp = 'white'
 typescriptNumber = 'white'
 typescriptMember = 'yellow'
 typescriptArrowFunc = 'fg'
 typescriptArrowFuncDef = 'fg'
 typescriptFuncTypeArrow = 'fg'
 typescriptObjectLiteral = 'fg'
 typescriptObjectColon = 'fg'
 typescriptCall = 'yellow'
 typescriptIdentifierName = 'yellow' 
 typescriptTypeReference = 'red'
 typescriptProp = 'white'
 typescriptParenExp = 'red'
 typescriptFuncType = 'yellow'
 
[tsx]
 htmlTag = 'fg'
 htmlTagName = 'fg'
 tsxTag = 'fg'
 tsxTagName = 'red'
 tsxAttrib = 'fg_vivid'
 tsxEqual = 'fg'
 tsxEscjs = 'yellow'
 
[markdown]
 markdownBlockquote = 'green'
 markdownCode = 'orange'
 markdownCodeBlock = 'orange'
 markdownCodeDelimiter = 'orange'
 markdownH1 = 'blue'
 markdownH2 = 'blue'
 markdownH3 = 'blue'
 markdownH4 = 'blue'
 markdownH5 = 'blue'
 markdownH6 = 'blue'
 markdownHeadingDelimiter = 'blue'
 markdownHeadingRule = 'fg - b'
 markdownId = 'white'
 markdownIdDeclaration = 'blue'
 markdownIdDelimiter = 'light_gray'
 markdownLinkDelimiter = 'light_gray'
 markdownBold = 'blue - b'
 markdownItalic = '- - i'
 markdownBoldItalic = 'white - bi'
 markdownListMarker = 'blue'
 markdownOrderedListMarker = 'blue'
 markdownRule = 'accent'
 markdownUrl = 'cyan - u'
 markdownLinkText = 'blue'
 markdownFootnote = 'orange'
 markdownFootnoteDefinition = 'orange'
 markdownEscape = 'white'

[Whichkey]
 WhichKey = 'white'
 WhichKeySeperator = 'green'
 WhichKeyGroup = 'blue'
 WhichKeyDesc = 'light_blue'
 WhichKeyFloat = '- dark'

[Git]
 SignAdd = 'sign_add'
 SignChange = 'sign_change'
 SignDelete = 'sign_delete'
 GitSignsAdd = 'sign_add'
 GitSignsChange = 'sign_change'
 GitSignsDelete = 'sign_delete'

[LSP]
 LspDiagnosticsDefaultError = 'error_red'
 LspDiagnosticsDefaultWarning = 'warning_orange'
 LspDiagnosticsDefaultInformation = 'info_white'
 LspDiagnosticsDefaultInfo = 'info_white'
 LspDiagnosticsDefaultHint = 'hint_blue'
 LspDiagnosticsVirtualTextError = 'error_red'
 LspDiagnosticsVirtualTextWarning = 'warning_orange'
 LspDiagnosticsVirtualTextInformation = 'info_white'
 LspDiagnosticsVirtualTextInfo = 'info_white'
 LspDiagnosticsVirtualTextHint = 'hint_blue'
 LspDiagnosticsFloatingError = 'error_red'
 LspDiagnosticsFloatingWarning = 'warning_orange'
 LspDiagnosticsFloatingInformation = 'info_white'
 LspDiagnosticsFloatingInfo = 'info_white'
 LspDiagnosticsFloatingHint = 'hint_blue'
 DiagnosticSignError = 'error_red'
 DiagnosticSignWarning = 'warning_orange'
 DiagnosticSignInformation = 'info_white'
 DiagnosticSignInfo = 'info_white'
 DiagnosticSignHint = 'hint_blue'
 LspDiagnosticsSignError = 'error_red'
 LspDiagnosticsSignWarning = 'warning_orange'
 LspDiagnosticsSignInformation = 'info_white'
 LspDiagnosticsSignInfo = 'info_white'
 LspDiagnosticsSignHint = 'hint_blue'
 LspDiagnosticsError = 'error_red'
 LspDiagnosticsWarning = 'warning_orange'
 LspDiagnosticsInformation = 'info_white'
 LspDiagnosticsInfo = 'info_white'
 LspDiagnosticsHint = 'hint_blue'
 LspDiagnosticsUnderlineError = '- - u'
 LspDiagnosticsUnderlineWarning = '- - u'
 LspDiagnosticsUnderlineInformation = '- - u'
 LspDiagnosticsUnderlineInfo = '- - u'
 LspDiagnosticsUnderlineHint = '- - u'
 LspReferenceRead = '- #2e303b'
 LspReferenceText = '- #2e303b'
 LspReferenceWrite = '- #2e303b'
 LspCodeLens = 'context - i'
 LspCodeLensSeparator = 'context - i'

[Telescope]
 TelescopeSelection = 'yellow'
 TelescopeMatching = 'info_white - b'
 TelescopeBorder = 'fg_vivid bg'

[NvimTree]
 NvimTreeFolderIcon = 'folder_blue'
 NvimTreeIndentMarker = '#c5c5c5'
 NvimTreeNormal = 'light_gray bg_dark'
 NvimTreeVertSplit = 'bg_dark bg_dark'
 NvimTreeFolderName = 'folder_blue'
 NvimTreeOpenedFolderName = 'folder_blue - bi'
 NvimTreeEmptyFolderName = 'gray - i'
 NvimTreeGitIgnored = 'gray - i'
 NvimTreeImageFile = 'light_gray'
 NvimTreeSpecialFile = 'orange'
 NvimTreeEndOfBuffer = 'bg_dark'
 NvimTreeCursorLine = '- #282b37'
 NvimTreeGitignoreIcon = '#E64A19'
 NvimTreeGitStaged = 'tree_sign_add'
 NvimTreeGitNew = 'tree_sign_add'
 NvimTreeGitRenamed = 'tree_sign_add'
 NvimTreeGitDeleted = 'sign_delete'
 NvimTreeGitMerge = 'tree_sign_change'
 NvimTreeGitDirty = 'tree_sign_change'

 NvimTreeSymlink = 'cyan'
 NvimTreeRootFolder = 'fg - b'
 NvimTreeExecFile = '#9FBA89'

[Buffer]
 BufferCurrent = 'fg bg'
 BufferCurrentIndex = 'fg bg'
 BufferCurrentMod = 'info_white bg'
 BufferCurrentSign = 'hint_blue bg'
 BufferCurrentTarget = 'red bg b'

 BufferVisible = 'fg bg'
 BufferVisibleIndex = 'fg bg'
 BufferVisibleMod = 'info_white bg'
 BufferVisibleSign = 'gray bg'
 BufferVisibleTarget = 'red bg b'

 BufferInactive = 'gray bg_dark'
 BufferInactiveIndex = 'gray bg_dark'
 BufferInactiveMod = 'info_white bg_dark'
 BufferInactiveSign = 'gray bg_dark'
 BufferInactiveTarget = 'red bg_dark b'

[StatusLine]
 StatusLine = 'line gray'
 StatusLineNC = 'line gray'
 StatusLineSeparator = 'line'
 StatusLineTerm = 'line'
 StatusLineTermNC = 'line'

[IndentBlankline]
 IndentBlanklineContextChar = 'context'
 IndentBlanklineContextStart = '- - u'
 IndentBlanklineChar = 'dark_gray'
 IndentBlanklineSpaceChar = 'cyan_test'
 IndentBlanklineSpaceCharBlankline = 'info_white'

[Dashboard]
 DashboardHeader = 'blue'
 DashboardCenter = 'white'
 DashboardFooter = 'cyan'

[Cmp]
 CmpItemAbbrDeprecated = 'gray - s'
 CmpItemAbbrMatch = 'ui3_blue'
 CmpItemAbbrMatchFuzzy = 'ui3_blue'
 CmpItemKindFunction = 'blue'
 CmpItemKindMethod = 'blue'
 CmpItemKindConstructor = 'cyan'
 CmpItemKindClass = 'cyan'
 CmpItemKindEnum = 'cyan'
 CmpItemKindEvent = 'white'
 CmpItemKindInterface = 'cyan'
 CmpItemKindStruct = 'cyan'
 CmpItemKindVariable = 'red'
 CmpItemKindField = 'red'
 CmpItemKindProperty = 'red'
 CmpItemKindEnumMember = 'orange'
 CmpItemKindConstant = 'orange'
 CmpItemKindKeyword = 'white'
 CmpItemKindModule = 'cyan'
 CmpItemKindValue = 'fg'
 CmpItemKindUnit = 'fg'
 CmpItemKindText = 'fg'
 CmpItemKindSnippet = 'white'
 CmpItemKindFile = 'fg'
 CmpItemKindFolder = 'fg'
 CmpItemKindColor = 'fg'
 CmpItemKindReference = 'fg'
 CmpItemKindOperator = 'fg'
 CmpItemKindTypeParameter = 'red'


[Netrw]
 netrwComment = 'fg' 
 netrwQuickHelp = 'fg'
 netrwHelpCommand = 'white'
 netrwDir = 'pink'
 netrwClassify = 'pink'
 netrwPlain = 'fg'
